export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const LOGOUT = "LOGOUT";
export const ADD_PODUCT = "ADD_PODUCT";
export const MODIFY_PODUCT_SHOW = "MODIFY_PODUCT_SHOW";
export const DELETE_PODUCT = "DELETE_PODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const LOADING = "LOADING";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const AUTH_FAILED = "AUTH_FAILED";
export const GET_PROFILE = "GET_PROFILE";
export const REGISTER_COMPANY = "REGISTER_COMPANY";
export const GET_PRODUCT_COMPANY = "GET_PRODUCT_COMPANY";
export const GET_COMPANIES = "GET_COMPANIES";
export const LOADING_COMPANIES = "LOADING_COMPANIES";
export const GET_ONE_COMPANY = "GET_ONE_COMPANY";
export const GET_PRODUCTS_OF_SPECEFIC_COMPANY =
  "GET_PRODUCTS_OF_SPECEFIC_COMPANY";
export const PRODUCT_FAILED = "PRODUCT_FAILED";
export const GET_ONE_COMPANY_FAILED = "GET_ONE_COMPANY_FAILED";
export const LOADING_GET_COMPANY = "LOADING_GET_COMPANY";
export const GET_PRODUCTS_OF_SPECEFIC_COMPANY_FAILED =
  "GET_PRODUCTS_OF_SPECEFIC_COMPANY_FAILED";
export const LOAODING_GET_PROFILE = "LOAODING_GET_PROFILE";
export const LOAODING_PROFILE = "LOAODING_PROFILE";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const VERFIY_TYPED_PASSWORD = "VERFIY_TYPED_PASSWORD";
export const LOAODING_CHECK_PASSWORD = "LOAODING_CHECK_PASSWORD";
export const GET_ONE_PRODUCT_OF_COMPANY = "GET_ONE_PRODUCT_OF_COMPANY";
export const LOADING_GET_ONE_PRODUCT = "LOADING_GET_ONE_PRODUCT";
export const MODIFY_PRODUCT = "MODIFY_PRODUCT";
export const GET_CLIENTS_BY_ADMIN = "GET_CLIENTS_BY_ADMIN";
export const GET_COMPANIES_BY_ADMIN = "GET_COMPANIES_BY_ADMIN";
export const CHOICE_TABLE_BY_ADMIN = "CHOICE_TABLE_BY_ADMIN";

export const SET_VERIFY_PASSWORD_FALSE = "SET_VERIFY_PASSWORD_FALSE";
export const GET_CODE_FROM_EMAIL = "GET_CODE_FROM_EMAIL";
export const GET_CODE_FROM_EMAIL_LOADING = "GET_CODE_FROM_EMAIL_LOADING";
export const CHECK_VALIDATION_CODE = "CHECK_VALIDATION_CODE";
export const LOADING_VALIDATION_CODE = "LOADING_VALIDATION_CODE";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";
export const RESET_PASSWORD_LOADING = "RESET_PASSWORD_LOADING";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGIN_FAILED_BANNED_USER = "LOGIN_FAILED_BANNED_USER";
export const RESET_BANNED_USER = "RESET_BANNED_USER";

export const SEND_MESSAGE_TO_ADMIN_LOADING = "SEND_MESSAGE_TO_ADMIN_LOADING";
export const ERROR_MESSAGE_SENDING = "ERROR_MESSAGE_SENDING";
export const SENDING_MESSAGE_SUCCESS = "SENDING_MESSAGE_SUCCESS";

export const GET_All_COMPANIES_LOADING = "GET_All_COMPANIES_LOADING";
export const GET_ALL_COMPANIES = "GET_ALL_COMPANIES_COMPANIES";

export const GET_LENGTH_COMPANY_INFO_LOADING =
  "GET_LENGTH_COMPANY_INFO_LOADING";
export const GET_LENGTH_COMPANY_INFO = "GET_LENGTH_COMPANY_INFO";

export const GET_ALL_BANNED_COMPANIES = "GET_ALL_BANNED_COMPANIES";
export const GET_ALL_BANNED_COMPANIES_LOADING =
  "GET_ALL_BANNED_COMPANIES_LOADING";

export const GET_ALL_VERIFIED_COMPANIES_LOADING =
  "GET_ALL_VERIFIED_COMPANIES_LOADING";

export const GET_ALL_VERIFIED_COMPANIES = "GET_ALL_VERIFIED_COMPANIES";

export const GET_ALL_CLIENT_LOADING = "GET_ALL_ALL_CLIENT_LOADING";
export const GET_ALL_CLIENT = "GET_ALL_ALL_CLIENT";

export const GET_BANN_CLIENT_LOADING = "GET_BANN_CLIENT_LOADING";
export const GET_BANN_CLIENT = "GET_BANN_CLIENT";

export const GET_ACTIVATED_CLIENT_LOADING = "GET_BANN_CLIENT_LOADING";
export const GET_ACTIVATED_CLIENT = "GET_ACTIVATED_CLIENT";

export const GET_LENGTH_CLIENT_INFO_LOADING = "GET_LENGTH_CLIENT_INFO_LOADING";
export const GET_LENGTH_CLIENT_INFO = "GET_LENGTH_CLIENT_INFO";

export const GET_MESSAGES_LOADING = "GET_MESSAGES_LOADING";
export const GET_MESSAGES = "BAN_VERIFY_USER";

export const DELETE_MESSAGE_LOADING = "DELETE_MESSAGE_LOADING";
export const DELETE_MESSAGE = "DELETE_MESSAGE";

export const ADD_TO_SHOP = "ADD_TO_SHOP";
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";

export const MAKE_ORDER_AS_DRAFT = "MAKE_ORDER_AS_DRAFT";
export const MAKE_ORDER_AS_DRAFT_LOADING = "MAKE_ORDER_AS_DRAFT_LOADING";
